spring.application.name=HospitalManagement


spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalProject
spring.datasource.username=postgres
spring.datasource.password=imbatman
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=DEBUG